<h1 align="left"> 🌐 Victor Leal Sousa</h1>

###

<p align="left">Minha jornada na tecnologia começou de forma clássica com um curso de informática básica que despertou minha curiosidade para o mundo digital. A partir daí, mergulhei de vez na área, cursando Hardware entre 2018 e 2021, e logo após iniciando a graduação em Análise e Desenvolvimento de Sistemas, onde venho consolidando minha base técnica e expandindo minhas habilidades como desenvolvedor.<br><br>Atualmente, atuo como desenvolvedor fullstack, com foco principal em Python, HTML, CSS, Js. Busco sempre aplicar boas práticas, desenvolver soluções funcionais e acompanhar as tendências do mercado para evoluir continuamente como profissional.<br><br>Tenho como objetivo transformar cada aprendizado em projetos reais ao longo da minha jornada em Engenharia de Software, colocando em prática o conhecimento adquirido e criando soluções que gerem impacto.</p>

###

<h2 align="left">Sobre mim</h2>

###

<p align="left">* Estudante de tecnologia <br>* Desenvolvedor de sistemas Junior<br>* Analista TI<br>* Habilidade em Microsoft 365</p>

###

<div align="left">
  <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg" height="40" alt="javascript logo"  />
  <img width="12" />
  <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg" height="40" alt="html5 logo"  />
  <img width="12" />
  <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg" height="40" alt="python logo"  />
  <img width="12" />
  <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg" height="40" alt="css logo"  />
</div>

###

<div align="center">
  <img src="https://github-readme-stats.vercel.app/api?username=Victor2001-dev&hide_title=false&hide_rank=false&show_icons=true&include_all_commits=true&count_private=true&disable_animations=false&theme=dracula&locale=en&hide_border=false&order=1" height="150" alt="stats graph"  />
</div>

###

<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/Victor2001-dev/Victor2001-dev/output/pacman-contribution-graph-dark.svg">
  <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/Victor2001-dev/Victor2001-dev/output/pacman-contribution-graph.svg">
  <img alt="pacman contribution graph" src="https://raw.githubusercontent.com/Victor2001-dev/Victor2001-dev/output/pacman-contribution-graph.svg">
</picture>

###
